stages:
  - build
  - deploy

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_TAG


variables:
  IMAGE: $LINBIT_DOCKER_REGISTRY/lbkeyper

build:
  stage: build
  image: ${LINBIT_DOCKER_REGISTRY}/container-tools:latest
  script:
    - DESTINATION_ARG="-t $IMAGE:$CI_COMMIT_REF_SLUG"
    - if [ "$CI_COMMIT_BRANCH" == "master" ]; then DESTINATION_ARG="$DESTINATION_ARG -t $IMAGE:latest" ; fi
    - if [ -n "$CI_COMMIT_TAG" ]; then DESTINATION_ARG="$DESTINATION_ARG -t $IMAGE:$CI_COMMIT_TAG" ; fi
    - docker buildx build --pull --push . --iidfile=image-id $DESTINATION_ARG
  artifacts:
    name: image-id
    paths:
      - image-id

deploy:
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_TAG
  stage: deploy
  image:
    name: docker.io/bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - kubectl set image deploy/lbkeyper lbkeyper=$IMAGE@$(cat image-id)
    - kubectl rollout status deploy/lbkeyper
