[users]
[users.alice]
keys = [
  "https://gitlab.acme.com/alice.keys",
  "ssh-ed25519 AAAAC3NzaC... alice@laptop"
]

[users.bob]
keys = [ "https://github.com/bob.keys" ]

[users.charlie]
keys = [ "https://github.com/charlie.keys" ]


[usergroups.admins]
members = [ "alice", "charlie" ]

[usergroups.pkgmaintainers]
members = [ "alice", "bob" ]

[servers.builder]
mapusers = true  # this allows non specified users to log in as well (e.g., alice@builder)
[servers.builder.users]
build = [ "@pkgmaintainers", "charlie" ]

[servergroups.www]
members = [ "www", "www2", "www3" ]
[servergroups.www.users]
root = [ "@admins" ]
uploader = [ "@pkgmaintainers" ]
